-- migrate:up

CREATE TABLE public.mapping_candidates (
    mapping_candidate_id bigint GENERATED BY DEFAULT AS IDENTITY,
    mapping_case_id bigint NOT NULL,
    mapping_case_observation_id bigint NOT NULL,
    candidate_scope text NOT NULL,
    candidate_card_id bigint NOT NULL,
    candidate_card_edition_id bigint,
    candidate_card_variant_id bigint,
    candidate_rank integer,
    candidate_score numeric(8, 6),
    generation_method text NOT NULL,
    evidence_level text NOT NULL,
    evidence_reference text NOT NULL,
    evidence_payload jsonb NOT NULL,
    candidate_state text NOT NULL DEFAULT 'active',
    state_reason_code text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    state_changed_at timestamp with time zone,

    CONSTRAINT mapping_candidates_pkey
        PRIMARY KEY (mapping_candidate_id),

    CONSTRAINT mapping_candidates_case_fk
        FOREIGN KEY (mapping_case_id)
        REFERENCES public.card_market_mapping_cases (mapping_case_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_candidates_observation_case_fk
        FOREIGN KEY (
            mapping_case_observation_id,
            mapping_case_id
        )
        REFERENCES public.mapping_case_observations (
            mapping_case_observation_id,
            mapping_case_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_candidates_card_fk
        FOREIGN KEY (candidate_card_id)
        REFERENCES public.cards (card_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_candidates_edition_fk
        FOREIGN KEY (
            candidate_card_edition_id,
            candidate_card_id
        )
        REFERENCES public.card_editions (
            card_edition_id,
            card_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_candidates_variant_fk
        FOREIGN KEY (
            candidate_card_variant_id,
            candidate_card_edition_id
        )
        REFERENCES public.card_variants (
            card_variant_id,
            card_edition_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_candidates_scope_check
        CHECK (
            candidate_scope IN (
                'card',
                'edition',
                'variant'
            )
        ),

    CONSTRAINT mapping_candidates_card_scope_check
        CHECK (
            candidate_scope <> 'card'
            OR (
                candidate_card_edition_id IS NULL
                AND candidate_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_candidates_edition_scope_check
        CHECK (
            candidate_scope <> 'edition'
            OR (
                candidate_card_edition_id IS NOT NULL
                AND candidate_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_candidates_variant_scope_check
        CHECK (
            candidate_scope <> 'variant'
            OR (
                candidate_card_edition_id IS NOT NULL
                AND candidate_card_variant_id IS NOT NULL
            )
        ),

    CONSTRAINT mapping_candidates_rank_check
        CHECK (
            candidate_rank IS NULL
            OR candidate_rank >= 1
        ),

    CONSTRAINT mapping_candidates_score_check
        CHECK (
            candidate_score IS NULL
            OR (
                candidate_score >= 0
                AND candidate_score <= 1
            )
        ),

    CONSTRAINT mapping_candidates_generation_method_check
        CHECK (
            generation_method = btrim(generation_method)
            AND generation_method IN (
                'direct_identifier_candidate',
                'normalized_name_match',
                'collector_number_match',
                'metaproduct_grouping',
                'validated_combined_rule',
                'manual_review'
            )
        ),

    CONSTRAINT mapping_candidates_evidence_level_check
        CHECK (
            evidence_level = btrim(evidence_level)
            AND evidence_level IN (
                'direct',
                'derived',
                'manual',
                'insufficient'
            )
        ),

    CONSTRAINT mapping_candidates_evidence_reference_check
        CHECK (
            evidence_reference = btrim(evidence_reference)
            AND evidence_reference <> ''
        ),

    CONSTRAINT mapping_candidates_state_check
        CHECK (
            candidate_state IN (
                'active',
                'selected',
                'rejected',
                'superseded',
                'withdrawn'
            )
        ),

    CONSTRAINT mapping_candidates_state_reason_code_check
        CHECK (
            state_reason_code IS NULL
            OR (
                state_reason_code = btrim(state_reason_code)
                AND state_reason_code <> ''
            )
        ),

    CONSTRAINT mapping_candidates_state_timestamp_check
        CHECK (
            (
                candidate_state = 'active'
                AND state_changed_at IS NULL
            )
            OR
            (
                candidate_state <> 'active'
                AND state_changed_at IS NOT NULL
            )
        ),

    CONSTRAINT mapping_candidates_state_reason_check
        CHECK (
            candidate_state NOT IN (
                'rejected',
                'superseded',
                'withdrawn'
            )
            OR state_reason_code IS NOT NULL
        )
);

CREATE UNIQUE INDEX mapping_candidates_card_target_key
    ON public.mapping_candidates (
        mapping_case_observation_id,
        candidate_card_id
    )
    WHERE candidate_scope = 'card';

CREATE UNIQUE INDEX mapping_candidates_edition_target_key
    ON public.mapping_candidates (
        mapping_case_observation_id,
        candidate_card_id,
        candidate_card_edition_id
    )
    WHERE candidate_scope = 'edition';

CREATE UNIQUE INDEX mapping_candidates_variant_target_key
    ON public.mapping_candidates (
        mapping_case_observation_id,
        candidate_card_id,
        candidate_card_edition_id,
        candidate_card_variant_id
    )
    WHERE candidate_scope = 'variant';

CREATE INDEX mapping_candidates_case_state_rank_idx
    ON public.mapping_candidates (
        mapping_case_id,
        candidate_state,
        candidate_rank
    );

CREATE INDEX mapping_candidates_observation_rank_idx
    ON public.mapping_candidates (
        mapping_case_observation_id,
        candidate_rank
    );

CREATE INDEX mapping_candidates_card_state_idx
    ON public.mapping_candidates (
        candidate_card_id,
        candidate_state
    );

CREATE INDEX mapping_candidates_method_evidence_idx
    ON public.mapping_candidates (
        generation_method,
        evidence_level
    );


-- migrate:down

DROP TABLE public.mapping_candidates;
