-- migrate:up

CREATE TABLE public.rejected_source_record_reasons (
    rejected_source_record_reason_id bigint GENERATED BY DEFAULT AS IDENTITY,
    rejected_source_record_id bigint NOT NULL,
    reason_code text NOT NULL,
    field_name text,
    reason_detail text NOT NULL,
    observed_value jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT rejected_source_record_reasons_pkey
        PRIMARY KEY (rejected_source_record_reason_id),

    CONSTRAINT rejected_source_record_reasons_identity_key
        UNIQUE (
            rejected_source_record_id,
            reason_code,
            field_name
        ),

    CONSTRAINT rejected_source_record_reasons_record_fk
        FOREIGN KEY (rejected_source_record_id)
        REFERENCES public.rejected_source_records (
            rejected_source_record_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT rejected_source_record_reasons_reason_code_check
        CHECK (
            reason_code = btrim(reason_code)
            AND reason_code <> ''
        ),

    CONSTRAINT rejected_source_record_reasons_field_name_check
        CHECK (
            field_name IS NULL
            OR (
                field_name = btrim(field_name)
                AND field_name <> ''
            )
        ),

    CONSTRAINT rejected_source_record_reasons_reason_detail_check
        CHECK (
            btrim(reason_detail) <> ''
        )
);

CREATE INDEX rejected_source_record_reasons_record_idx
    ON public.rejected_source_record_reasons (
        rejected_source_record_id
    );

CREATE INDEX rejected_source_record_reasons_code_idx
    ON public.rejected_source_record_reasons (
        reason_code
    );


-- migrate:down

DROP TABLE public.rejected_source_record_reasons;
