-- migrate:up

ALTER TABLE public.card_market_mapping_cases
    ADD CONSTRAINT card_market_mapping_cases_hierarchy_key
    UNIQUE (
        mapping_case_id,
        market_product_id
    );

CREATE TABLE public.card_market_product_mappings (
    card_market_product_mapping_id bigint GENERATED BY DEFAULT AS IDENTITY,
    mapping_case_id bigint NOT NULL,
    market_product_id bigint NOT NULL,
    card_id bigint NOT NULL,
    card_edition_id bigint,
    card_variant_id bigint,
    confirmation_scope text NOT NULL,
    confirmation_method text NOT NULL,
    evidence_level text NOT NULL,
    evidence_reference text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    superseded_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT card_market_product_mappings_pkey
        PRIMARY KEY (card_market_product_mapping_id),

    CONSTRAINT card_market_product_mappings_case_product_fk
        FOREIGN KEY (
            mapping_case_id,
            market_product_id
        )
        REFERENCES public.card_market_mapping_cases (
            mapping_case_id,
            market_product_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_market_product_mappings_market_product_fk
        FOREIGN KEY (market_product_id)
        REFERENCES public.market_products (market_product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_market_product_mappings_card_fk
        FOREIGN KEY (card_id)
        REFERENCES public.cards (card_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_market_product_mappings_edition_fk
        FOREIGN KEY (
            card_edition_id,
            card_id
        )
        REFERENCES public.card_editions (
            card_edition_id,
            card_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_market_product_mappings_variant_fk
        FOREIGN KEY (
            card_variant_id,
            card_edition_id
        )
        REFERENCES public.card_variants (
            card_variant_id,
            card_edition_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_market_product_mappings_scope_check
        CHECK (
            confirmation_scope IN (
                'card',
                'edition',
                'variant'
            )
        ),

    CONSTRAINT card_market_product_mappings_method_check
        CHECK (
            confirmation_method = btrim(confirmation_method)
            AND confirmation_method IN (
                'direct_source_identifier',
                'explicit_source_relationship',
                'validated_derived_rule',
                'manual_review'
            )
        ),

    CONSTRAINT card_market_product_mappings_evidence_level_check
        CHECK (
            evidence_level = btrim(evidence_level)
            AND evidence_level IN (
                'direct',
                'derived',
                'manual'
            )
        ),

    CONSTRAINT card_market_product_mappings_evidence_reference_check
        CHECK (
            evidence_reference = btrim(evidence_reference)
            AND evidence_reference <> ''
        ),

    CONSTRAINT card_market_product_mappings_card_scope_check
        CHECK (
            confirmation_scope <> 'card'
            OR (
                card_edition_id IS NULL
                AND card_variant_id IS NULL
            )
        ),

    CONSTRAINT card_market_product_mappings_edition_scope_check
        CHECK (
            confirmation_scope <> 'edition'
            OR (
                card_edition_id IS NOT NULL
                AND card_variant_id IS NULL
            )
        ),

    CONSTRAINT card_market_product_mappings_variant_scope_check
        CHECK (
            confirmation_scope <> 'variant'
            OR (
                card_edition_id IS NOT NULL
                AND card_variant_id IS NOT NULL
            )
        ),

    CONSTRAINT card_market_product_mappings_lifecycle_check
        CHECK (
            (
                is_active = true
                AND superseded_at IS NULL
            )
            OR
            (
                is_active = false
                AND superseded_at IS NOT NULL
            )
        )
);

CREATE UNIQUE INDEX card_market_product_mappings_active_product_key
    ON public.card_market_product_mappings (market_product_id)
    WHERE is_active = true;

CREATE INDEX card_market_product_mappings_card_active_idx
    ON public.card_market_product_mappings (
        card_id,
        is_active
    );

CREATE INDEX card_market_product_mappings_edition_active_idx
    ON public.card_market_product_mappings (
        card_edition_id,
        is_active
    )
    WHERE card_edition_id IS NOT NULL;

CREATE INDEX card_market_product_mappings_variant_active_idx
    ON public.card_market_product_mappings (
        card_variant_id,
        is_active
    )
    WHERE card_variant_id IS NOT NULL;

CREATE INDEX card_market_product_mappings_case_idx
    ON public.card_market_product_mappings (mapping_case_id);

CREATE INDEX card_market_product_mappings_scope_active_idx
    ON public.card_market_product_mappings (
        confirmation_scope,
        is_active
    );


-- migrate:down

DROP TABLE public.card_market_product_mappings;

ALTER TABLE public.card_market_mapping_cases
    DROP CONSTRAINT card_market_mapping_cases_hierarchy_key;
