-- migrate:up

CREATE TABLE public.mapping_case_observations (
    mapping_case_observation_id bigint GENERATED BY DEFAULT AS IDENTITY,
    mapping_case_id bigint NOT NULL,
    import_run_id bigint,
    source_record_reference text NOT NULL,
    observation_status text NOT NULL,
    proposed_confirmation_scope text,
    proposed_card_id bigint,
    proposed_card_edition_id bigint,
    proposed_card_variant_id bigint,
    confirmation_method text,
    evidence_level text NOT NULL,
    evidence_reference text NOT NULL,
    evidence_payload jsonb NOT NULL,
    observation_result text NOT NULL,
    result_reason_code text,
    result_reason_detail text,
    observed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT mapping_case_observations_pkey
        PRIMARY KEY (mapping_case_observation_id),

    CONSTRAINT mapping_case_observations_event_key
        UNIQUE NULLS NOT DISTINCT (
            mapping_case_id,
            import_run_id,
            source_record_reference
        ),

    CONSTRAINT mapping_case_observations_case_fk
        FOREIGN KEY (mapping_case_id)
        REFERENCES public.card_market_mapping_cases (mapping_case_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_case_observations_import_run_fk
        FOREIGN KEY (import_run_id)
        REFERENCES public.import_runs (import_run_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_case_observations_card_fk
        FOREIGN KEY (proposed_card_id)
        REFERENCES public.cards (card_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_case_observations_edition_fk
        FOREIGN KEY (
            proposed_card_edition_id,
            proposed_card_id
        )
        REFERENCES public.card_editions (
            card_edition_id,
            card_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_case_observations_variant_fk
        FOREIGN KEY (
            proposed_card_variant_id,
            proposed_card_edition_id
        )
        REFERENCES public.card_variants (
            card_variant_id,
            card_edition_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_case_observations_source_reference_check
        CHECK (
            source_record_reference = btrim(source_record_reference)
            AND source_record_reference <> ''
        ),

    CONSTRAINT mapping_case_observations_status_check
        CHECK (
            observation_status IN (
                'confirmed',
                'candidate',
                'unmatched',
                'ambiguous',
                'excluded',
                'unmatched_duplicate_candidate'
            )
        ),

    CONSTRAINT mapping_case_observations_scope_check
        CHECK (
            proposed_confirmation_scope IS NULL
            OR proposed_confirmation_scope IN (
                'card',
                'edition',
                'variant'
            )
        ),

    CONSTRAINT mapping_case_observations_method_check
        CHECK (
            confirmation_method IS NULL
            OR confirmation_method IN (
                'direct_source_identifier',
                'explicit_source_relationship',
                'validated_derived_rule',
                'manual_review'
            )
        ),

    CONSTRAINT mapping_case_observations_evidence_level_check
        CHECK (
            evidence_level IN (
                'direct',
                'derived',
                'manual',
                'insufficient'
            )
        ),

    CONSTRAINT mapping_case_observations_evidence_reference_check
        CHECK (
            evidence_reference = btrim(evidence_reference)
            AND evidence_reference <> ''
        ),

    CONSTRAINT mapping_case_observations_result_check
        CHECK (
            observation_result IN (
                'accepted_transition',
                'accepted_support',
                'accepted_more_specific',
                'recorded_weaker',
                'recorded_conflict',
                'recorded_no_change',
                'rejected_transition'
            )
        ),

    CONSTRAINT mapping_case_observations_result_reason_code_check
        CHECK (
            result_reason_code IS NULL
            OR (
                result_reason_code = btrim(result_reason_code)
                AND result_reason_code <> ''
            )
        ),

    CONSTRAINT mapping_case_observations_result_reason_detail_check
        CHECK (
            result_reason_detail IS NULL
            OR btrim(result_reason_detail) <> ''
        ),

    CONSTRAINT mapping_case_observations_confirmed_state_check
        CHECK (
            observation_status <> 'confirmed'
            OR (
                proposed_confirmation_scope IS NOT NULL
                AND proposed_card_id IS NOT NULL
                AND confirmation_method IS NOT NULL
                AND evidence_level <> 'insufficient'
            )
        ),

    CONSTRAINT mapping_case_observations_nonconfirmed_method_check
        CHECK (
            observation_status = 'confirmed'
            OR (
                proposed_confirmation_scope IS NULL
                AND confirmation_method IS NULL
            )
        ),

    CONSTRAINT mapping_case_observations_card_scope_check
        CHECK (
            proposed_confirmation_scope <> 'card'
            OR (
                proposed_card_id IS NOT NULL
                AND proposed_card_edition_id IS NULL
                AND proposed_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_case_observations_edition_scope_check
        CHECK (
            proposed_confirmation_scope <> 'edition'
            OR (
                proposed_card_id IS NOT NULL
                AND proposed_card_edition_id IS NOT NULL
                AND proposed_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_case_observations_variant_scope_check
        CHECK (
            proposed_confirmation_scope <> 'variant'
            OR (
                proposed_card_id IS NOT NULL
                AND proposed_card_edition_id IS NOT NULL
                AND proposed_card_variant_id IS NOT NULL
            )
        ),

    CONSTRAINT mapping_case_observations_reason_required_check
        CHECK (
            observation_result NOT IN (
                'recorded_weaker',
                'recorded_conflict',
                'rejected_transition'
            )
            OR result_reason_code IS NOT NULL
        )
);

CREATE INDEX mapping_case_observations_case_observed_idx
    ON public.mapping_case_observations (
        mapping_case_id,
        observed_at DESC
    );

CREATE INDEX mapping_case_observations_import_run_idx
    ON public.mapping_case_observations (
        import_run_id
    )
    WHERE import_run_id IS NOT NULL;

CREATE INDEX mapping_case_observations_status_result_idx
    ON public.mapping_case_observations (
        observation_status,
        observation_result
    );

CREATE INDEX mapping_case_observations_proposed_card_idx
    ON public.mapping_case_observations (
        proposed_card_id
    )
    WHERE proposed_card_id IS NOT NULL;

ALTER TABLE public.mapping_case_observations
    ADD CONSTRAINT mapping_case_observations_hierarchy_key
    UNIQUE (
        mapping_case_observation_id,
        mapping_case_id
    );

ALTER TABLE public.card_market_mapping_cases
    ADD CONSTRAINT card_market_mapping_cases_status_observation_fk
    FOREIGN KEY (status_source_observation_id)
    REFERENCES public.mapping_case_observations (
        mapping_case_observation_id
    )
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;


-- migrate:down

ALTER TABLE public.card_market_mapping_cases
    DROP CONSTRAINT card_market_mapping_cases_status_observation_fk;

DROP TABLE public.mapping_case_observations;
