-- migrate:up

CREATE TABLE public.staging_market_mappings (
    staging_market_mapping_id bigint GENERATED BY DEFAULT AS IDENTITY,
    import_run_id bigint NOT NULL,
    source_record_reference text NOT NULL,
    market_source_system text NOT NULL,
    source_product_id text,
    catalogue_source_system text,
    source_card_id text,
    source_edition_code text,
    language_code text,
    finish_code text,
    finish_detail text,
    proposed_status text,
    confirmation_scope text,
    confirmation_method text,
    evidence_level text,
    evidence_reference text NOT NULL,
    evidence_payload jsonb NOT NULL,
    raw_payload jsonb NOT NULL,
    record_checksum text,
    normalization_status text NOT NULL DEFAULT 'pending',
    validation_status text NOT NULL DEFAULT 'pending',
    validation_completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT staging_market_mappings_pkey
        PRIMARY KEY (staging_market_mapping_id),

    CONSTRAINT staging_market_mappings_source_record_key
        UNIQUE (
            import_run_id,
            source_record_reference
        ),

    CONSTRAINT staging_market_mappings_import_run_fk
        FOREIGN KEY (import_run_id)
        REFERENCES public.import_runs (import_run_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT staging_market_mappings_source_record_reference_check
        CHECK (
            source_record_reference = btrim(source_record_reference)
            AND source_record_reference <> ''
        ),

    CONSTRAINT staging_market_mappings_market_source_system_check
        CHECK (
            market_source_system = btrim(market_source_system)
            AND market_source_system = 'cardmarket'
        ),

    CONSTRAINT staging_market_mappings_source_product_id_check
        CHECK (
            source_product_id IS NULL
            OR (
                source_product_id = btrim(source_product_id)
                AND source_product_id <> ''
            )
        ),

    CONSTRAINT staging_market_mappings_catalogue_source_system_check
        CHECK (
            catalogue_source_system IS NULL
            OR (
                catalogue_source_system = btrim(catalogue_source_system)
                AND catalogue_source_system = 'pokemon_tcg_data'
            )
        ),

    CONSTRAINT staging_market_mappings_source_card_id_check
        CHECK (
            source_card_id IS NULL
            OR (
                source_card_id = btrim(source_card_id)
                AND source_card_id <> ''
            )
        ),

    CONSTRAINT staging_market_mappings_source_edition_code_check
        CHECK (
            source_edition_code IS NULL
            OR (
                source_edition_code = btrim(source_edition_code)
                AND source_edition_code <> ''
            )
        ),

    CONSTRAINT staging_market_mappings_language_code_check
        CHECK (
            language_code IS NULL
            OR (
                language_code = btrim(language_code)
                AND language_code IN ('en', 'de')
            )
        ),

    CONSTRAINT staging_market_mappings_finish_code_check
        CHECK (
            finish_code IS NULL
            OR (
                finish_code = btrim(finish_code)
                AND finish_code IN (
                    'normal',
                    'reverse_holo',
                    'holo',
                    'other'
                )
            )
        ),

    CONSTRAINT staging_market_mappings_finish_detail_check
        CHECK (
            (
                finish_code = 'other'
                AND finish_detail IS NOT NULL
                AND btrim(finish_detail) <> ''
            )
            OR
            (
                finish_code IS DISTINCT FROM 'other'
                AND finish_detail IS NULL
            )
        ),

    CONSTRAINT staging_market_mappings_proposed_status_check
        CHECK (
            proposed_status IS NULL
            OR (
                proposed_status = btrim(proposed_status)
                AND proposed_status IN (
                    'confirmed',
                    'candidate',
                    'unmatched',
                    'ambiguous',
                    'excluded',
                    'unmatched_duplicate_candidate'
                )
            )
        ),

    CONSTRAINT staging_market_mappings_confirmation_scope_check
        CHECK (
            confirmation_scope IS NULL
            OR (
                confirmation_scope = btrim(confirmation_scope)
                AND confirmation_scope IN (
                    'card',
                    'edition',
                    'variant'
                )
            )
        ),

    CONSTRAINT staging_market_mappings_confirmation_method_check
        CHECK (
            confirmation_method IS NULL
            OR (
                confirmation_method = btrim(confirmation_method)
                AND confirmation_method IN (
                    'direct_source_identifier',
                    'explicit_source_relationship',
                    'validated_derived_rule',
                    'manual_review'
                )
            )
        ),

    CONSTRAINT staging_market_mappings_evidence_level_check
        CHECK (
            evidence_level IS NULL
            OR (
                evidence_level = btrim(evidence_level)
                AND evidence_level IN (
                    'direct',
                    'derived',
                    'manual',
                    'insufficient'
                )
            )
        ),

    CONSTRAINT staging_market_mappings_evidence_reference_check
        CHECK (
            evidence_reference = btrim(evidence_reference)
            AND evidence_reference <> ''
        ),

    CONSTRAINT staging_market_mappings_record_checksum_check
        CHECK (
            record_checksum IS NULL
            OR (
                record_checksum = btrim(record_checksum)
                AND record_checksum <> ''
            )
        ),

    CONSTRAINT staging_market_mappings_normalization_status_check
        CHECK (
            normalization_status IN (
                'pending',
                'normalized',
                'normalization_failed'
            )
        ),

    CONSTRAINT staging_market_mappings_validation_status_check
        CHECK (
            validation_status IN (
                'pending',
                'valid',
                'rejected'
            )
        ),

    CONSTRAINT staging_market_mappings_validation_state_check
        CHECK (
            validation_status <> 'valid'
            OR normalization_status = 'normalized'
        ),

    CONSTRAINT staging_market_mappings_validation_timestamp_check
        CHECK (
            (
                validation_status = 'pending'
                AND validation_completed_at IS NULL
            )
            OR
            (
                validation_status IN ('valid', 'rejected')
                AND validation_completed_at IS NOT NULL
            )
        ),

    CONSTRAINT staging_market_mappings_confirmed_fields_check
        CHECK (
            proposed_status <> 'confirmed'
            OR (
                source_product_id IS NOT NULL
                AND catalogue_source_system IS NOT NULL
                AND source_card_id IS NOT NULL
                AND confirmation_scope IS NOT NULL
                AND confirmation_method IS NOT NULL
                AND evidence_level IS NOT NULL
                AND evidence_level <> 'insufficient'
            )
        ),

    CONSTRAINT staging_market_mappings_nonconfirmed_scope_check
        CHECK (
            proposed_status IS NULL
            OR proposed_status = 'confirmed'
            OR (
                confirmation_scope IS NULL
                AND confirmation_method IS NULL
            )
        ),

    CONSTRAINT staging_market_mappings_card_scope_check
        CHECK (
            confirmation_scope <> 'card'
            OR (
                source_card_id IS NOT NULL
                AND source_edition_code IS NULL
                AND language_code IS NULL
                AND finish_code IS NULL
                AND finish_detail IS NULL
            )
        ),

    CONSTRAINT staging_market_mappings_edition_scope_check
        CHECK (
            confirmation_scope <> 'edition'
            OR (
                source_card_id IS NOT NULL
                AND source_edition_code IS NOT NULL
                AND language_code IS NULL
                AND finish_code IS NULL
                AND finish_detail IS NULL
            )
        ),

    CONSTRAINT staging_market_mappings_variant_scope_check
        CHECK (
            confirmation_scope <> 'variant'
            OR (
                source_card_id IS NOT NULL
                AND source_edition_code IS NOT NULL
                AND language_code IS NOT NULL
                AND finish_code IS NOT NULL
            )
        ),

    CONSTRAINT staging_market_mappings_valid_record_check
        CHECK (
            validation_status <> 'valid'
            OR (
                proposed_status IS NOT NULL
                AND source_product_id IS NOT NULL
            )
        )
);

CREATE INDEX staging_market_mappings_import_run_status_idx
    ON public.staging_market_mappings (
        import_run_id,
        validation_status
    );

CREATE INDEX staging_market_mappings_source_product_idx
    ON public.staging_market_mappings (
        import_run_id,
        market_source_system,
        source_product_id
    )
    WHERE source_product_id IS NOT NULL;

CREATE INDEX staging_market_mappings_source_card_idx
    ON public.staging_market_mappings (
        import_run_id,
        catalogue_source_system,
        source_card_id
    )
    WHERE source_card_id IS NOT NULL;

CREATE INDEX staging_market_mappings_proposed_status_idx
    ON public.staging_market_mappings (
        import_run_id,
        proposed_status
    )
    WHERE proposed_status IS NOT NULL;

CREATE INDEX staging_market_mappings_pending_idx
    ON public.staging_market_mappings (import_run_id)
    WHERE normalization_status = 'pending'
       OR validation_status = 'pending';


-- migrate:down

DROP TABLE public.staging_market_mappings;
