-- migrate:up

CREATE TABLE public.card_market_mapping_cases (
    mapping_case_id bigint GENERATED BY DEFAULT AS IDENTITY,
    market_product_id bigint NOT NULL,
    current_status text NOT NULL DEFAULT 'unmatched',
    current_confirmation_scope text,
    current_card_id bigint,
    current_card_edition_id bigint,
    current_card_variant_id bigint,
    status_source_observation_id bigint,
    first_observed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_observed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT card_market_mapping_cases_pkey
        PRIMARY KEY (mapping_case_id),

    CONSTRAINT card_market_mapping_cases_market_product_key
        UNIQUE (market_product_id),

    CONSTRAINT card_market_mapping_cases_market_product_fk
        FOREIGN KEY (market_product_id)
        REFERENCES public.market_products (market_product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_market_mapping_cases_current_card_fk
        FOREIGN KEY (current_card_id)
        REFERENCES public.cards (card_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_market_mapping_cases_current_edition_fk
        FOREIGN KEY (
            current_card_edition_id,
            current_card_id
        )
        REFERENCES public.card_editions (
            card_edition_id,
            card_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_market_mapping_cases_current_variant_fk
        FOREIGN KEY (
            current_card_variant_id,
            current_card_edition_id
        )
        REFERENCES public.card_variants (
            card_variant_id,
            card_edition_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_market_mapping_cases_status_check
        CHECK (
            current_status IN (
                'confirmed',
                'candidate',
                'unmatched',
                'ambiguous',
                'excluded',
                'unmatched_duplicate_candidate'
            )
        ),

    CONSTRAINT card_market_mapping_cases_scope_check
        CHECK (
            current_confirmation_scope IS NULL
            OR current_confirmation_scope IN (
                'card',
                'edition',
                'variant'
            )
        ),

    CONSTRAINT card_market_mapping_cases_confirmation_state_check
        CHECK (
            (
                current_status = 'confirmed'
                AND current_confirmation_scope IS NOT NULL
                AND current_card_id IS NOT NULL
                AND resolved_at IS NOT NULL
            )
            OR
            (
                current_status <> 'confirmed'
                AND current_confirmation_scope IS NULL
                AND current_card_id IS NULL
                AND current_card_edition_id IS NULL
                AND current_card_variant_id IS NULL
            )
        ),

    CONSTRAINT card_market_mapping_cases_card_scope_check
        CHECK (
            current_confirmation_scope <> 'card'
            OR (
                current_card_id IS NOT NULL
                AND current_card_edition_id IS NULL
                AND current_card_variant_id IS NULL
            )
        ),

    CONSTRAINT card_market_mapping_cases_edition_scope_check
        CHECK (
            current_confirmation_scope <> 'edition'
            OR (
                current_card_id IS NOT NULL
                AND current_card_edition_id IS NOT NULL
                AND current_card_variant_id IS NULL
            )
        ),

    CONSTRAINT card_market_mapping_cases_variant_scope_check
        CHECK (
            current_confirmation_scope <> 'variant'
            OR (
                current_card_id IS NOT NULL
                AND current_card_edition_id IS NOT NULL
                AND current_card_variant_id IS NOT NULL
            )
        ),

    CONSTRAINT card_market_mapping_cases_resolved_state_check
        CHECK (
            (
                current_status IN (
                    'confirmed',
                    'excluded',
                    'unmatched_duplicate_candidate'
                )
                AND resolved_at IS NOT NULL
            )
            OR
            (
                current_status IN (
                    'candidate',
                    'unmatched',
                    'ambiguous'
                )
                AND resolved_at IS NULL
            )
        ),

    CONSTRAINT card_market_mapping_cases_timestamp_order_check
        CHECK (
            first_observed_at <= last_observed_at
            AND (
                resolved_at IS NULL
                OR first_observed_at <= resolved_at
            )
        )
);

CREATE INDEX card_market_mapping_cases_status_idx
    ON public.card_market_mapping_cases (current_status);

CREATE INDEX card_market_mapping_cases_current_card_idx
    ON public.card_market_mapping_cases (current_card_id)
    WHERE current_card_id IS NOT NULL;

CREATE INDEX card_market_mapping_cases_unresolved_idx
    ON public.card_market_mapping_cases (
        current_status,
        last_observed_at
    )
    WHERE current_status IN (
        'candidate',
        'unmatched',
        'ambiguous'
    );


-- migrate:down

DROP TABLE public.card_market_mapping_cases;
