-- migrate:up

CREATE TABLE public.wishlist_items (
    wishlist_item_id bigint GENERATED BY DEFAULT AS IDENTITY,
    card_id bigint NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    notes text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT wishlist_items_pkey
        PRIMARY KEY (wishlist_item_id),

    CONSTRAINT wishlist_items_card_key
        UNIQUE (card_id),

    CONSTRAINT wishlist_items_card_fk
        FOREIGN KEY (card_id)
        REFERENCES public.cards (card_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT wishlist_items_quantity_check
        CHECK (quantity >= 1),

    CONSTRAINT wishlist_items_notes_check
        CHECK (
            notes IS NULL
            OR btrim(notes) <> ''
        )
);


-- migrate:down

DROP TABLE public.wishlist_items;
