-- migrate:up

CREATE TABLE public.import_record_outcomes (
    import_record_outcome_id bigint GENERATED BY DEFAULT AS IDENTITY,
    import_run_id bigint NOT NULL,
    entity_type text NOT NULL,
    source_system text,
    source_entity_id text,
    source_record_reference text,
    production_entity_id bigint,
    outcome_type text NOT NULL,
    reason_code text,
    reason_detail text,
    change_summary jsonb,
    recorded_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT import_record_outcomes_pkey
        PRIMARY KEY (import_record_outcome_id),

    CONSTRAINT import_record_outcomes_import_run_fk
        FOREIGN KEY (import_run_id)
        REFERENCES public.import_runs (import_run_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT import_record_outcomes_entity_type_check
        CHECK (
            entity_type = btrim(entity_type)
            AND entity_type IN (
                'expansion',
                'expansion_source_identifier',
                'card',
                'card_edition',
                'card_variant',
                'market_product',
                'card_market_product_mapping',
                'market_price_snapshot'
            )
        ),

    CONSTRAINT import_record_outcomes_source_identity_check
        CHECK (
            (
                source_system IS NULL
                AND source_entity_id IS NULL
            )
            OR
            (
                source_system IS NOT NULL
                AND source_system = btrim(source_system)
                AND source_system IN (
                    'pokemon_tcg_data',
                    'cardmarket'
                )
                AND source_entity_id IS NOT NULL
                AND source_entity_id = btrim(source_entity_id)
                AND source_entity_id <> ''
            )
        ),

    CONSTRAINT import_record_outcomes_source_record_reference_check
        CHECK (
            source_record_reference IS NULL
            OR (
                source_record_reference = btrim(source_record_reference)
                AND source_record_reference <> ''
            )
        ),

    CONSTRAINT import_record_outcomes_outcome_type_check
        CHECK (
            outcome_type = btrim(outcome_type)
            AND outcome_type IN (
                'inserted',
                'updated',
                'unchanged',
                'missing',
                'retired',
                'reactivated',
                'conflict',
                'skipped'
            )
        ),

    CONSTRAINT import_record_outcomes_reason_code_check
        CHECK (
            reason_code IS NULL
            OR (
                reason_code = btrim(reason_code)
                AND reason_code <> ''
            )
        ),

    CONSTRAINT import_record_outcomes_reason_detail_check
        CHECK (
            reason_detail IS NULL
            OR btrim(reason_detail) <> ''
        ),

    CONSTRAINT import_record_outcomes_identity_check
        CHECK (
            source_entity_id IS NOT NULL
            OR production_entity_id IS NOT NULL
        ),

    CONSTRAINT import_record_outcomes_production_identity_check
        CHECK (
            outcome_type NOT IN (
                'updated',
                'unchanged',
                'missing',
                'retired',
                'reactivated'
            )
            OR production_entity_id IS NOT NULL
        ),

    CONSTRAINT import_record_outcomes_inserted_identity_check
        CHECK (
            outcome_type <> 'inserted'
            OR production_entity_id IS NOT NULL
        ),

    CONSTRAINT import_record_outcomes_missing_reason_check
        CHECK (
            outcome_type <> 'missing'
            OR reason_code IS NOT NULL
        ),

    CONSTRAINT import_record_outcomes_conflict_reason_check
        CHECK (
            outcome_type <> 'conflict'
            OR reason_code IS NOT NULL
        ),

    CONSTRAINT import_record_outcomes_skipped_reason_check
        CHECK (
            outcome_type <> 'skipped'
            OR reason_code IS NOT NULL
        )
);

CREATE INDEX import_record_outcomes_run_entity_outcome_idx
    ON public.import_record_outcomes (
        import_run_id,
        entity_type,
        outcome_type
    );

CREATE INDEX import_record_outcomes_production_entity_idx
    ON public.import_record_outcomes (
        entity_type,
        production_entity_id,
        import_run_id
    )
    WHERE production_entity_id IS NOT NULL;

CREATE INDEX import_record_outcomes_source_entity_idx
    ON public.import_record_outcomes (
        source_system,
        source_entity_id,
        import_run_id
    )
    WHERE source_system IS NOT NULL
      AND source_entity_id IS NOT NULL;


-- migrate:down

DROP TABLE public.import_record_outcomes;
