-- migrate:up

CREATE TABLE public.expansions (
    expansion_id bigint GENERATED BY DEFAULT AS IDENTITY,
    expansion_key text NOT NULL,
    name text NOT NULL,
    series_name text,
    printed_total integer,
    total integer,
    release_date date,
    symbol_url text,
    logo_url text,
    is_active boolean NOT NULL DEFAULT true,
    retired_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT expansions_pkey
        PRIMARY KEY (expansion_id),

    CONSTRAINT expansions_expansion_key_key
        UNIQUE (expansion_key),

    CONSTRAINT expansions_expansion_key_check
        CHECK (
            expansion_key = btrim(expansion_key)
            AND expansion_key <> ''
        ),

    CONSTRAINT expansions_name_check
        CHECK (btrim(name) <> ''),

    CONSTRAINT expansions_series_name_check
        CHECK (
            series_name IS NULL
            OR btrim(series_name) <> ''
        ),

    CONSTRAINT expansions_symbol_url_check
        CHECK (
            symbol_url IS NULL
            OR btrim(symbol_url) <> ''
        ),

    CONSTRAINT expansions_logo_url_check
        CHECK (
            logo_url IS NULL
            OR btrim(logo_url) <> ''
        ),

    CONSTRAINT expansions_printed_total_check
        CHECK (
            printed_total IS NULL
            OR printed_total >= 0
        ),

    CONSTRAINT expansions_total_check
        CHECK (
            total IS NULL
            OR total >= 0
        ),

    CONSTRAINT expansions_set_size_check
        CHECK (
            printed_total IS NULL
            OR total IS NULL
            OR printed_total <= total
        ),

    CONSTRAINT expansions_lifecycle_check
        CHECK (
            (is_active = true AND retired_at IS NULL)
            OR
            (is_active = false AND retired_at IS NOT NULL)
        )
);

CREATE TABLE public.expansion_source_identifiers (
    expansion_source_identifier_id bigint GENERATED BY DEFAULT AS IDENTITY,
    expansion_id bigint NOT NULL,
    source_system text NOT NULL,
    source_expansion_id text NOT NULL,
    source_name text,
    source_url text,
    source_payload jsonb,
    is_active boolean NOT NULL DEFAULT true,
    retired_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT expansion_source_identifiers_pkey
        PRIMARY KEY (expansion_source_identifier_id),

    CONSTRAINT expansion_source_identifiers_source_identity_key
        UNIQUE (source_system, source_expansion_id),

    CONSTRAINT expansion_source_identifiers_expansion_fk
        FOREIGN KEY (expansion_id)
        REFERENCES public.expansions (expansion_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT expansion_source_identifiers_source_system_check
        CHECK (
            source_system = btrim(source_system)
            AND source_system IN ('pokemon_tcg_data', 'cardmarket')
        ),

    CONSTRAINT expansion_source_identifiers_source_expansion_id_check
        CHECK (
            source_expansion_id = btrim(source_expansion_id)
            AND source_expansion_id <> ''
        ),

    CONSTRAINT expansion_source_identifiers_source_name_check
        CHECK (
            source_name IS NULL
            OR btrim(source_name) <> ''
        ),

    CONSTRAINT expansion_source_identifiers_source_url_check
        CHECK (
            source_url IS NULL
            OR btrim(source_url) <> ''
        ),

    CONSTRAINT expansion_source_identifiers_lifecycle_check
        CHECK (
            (is_active = true AND retired_at IS NULL)
            OR
            (is_active = false AND retired_at IS NOT NULL)
        )
);

CREATE TABLE public.cards (
    card_id bigint GENERATED BY DEFAULT AS IDENTITY,
    expansion_id bigint NOT NULL,
    source_system text NOT NULL,
    source_card_id text NOT NULL,
    collector_number text NOT NULL,
    name text NOT NULL,
    rarity text,
    image_small_url text,
    image_large_url text,
    is_active boolean NOT NULL DEFAULT true,
    retired_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT cards_pkey
        PRIMARY KEY (card_id),

    CONSTRAINT cards_source_identity_key
        UNIQUE (source_system, source_card_id),

    CONSTRAINT cards_expansion_fk
        FOREIGN KEY (expansion_id)
        REFERENCES public.expansions (expansion_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT cards_source_system_check
        CHECK (
            source_system = btrim(source_system)
            AND source_system IN ('pokemon_tcg_data', 'cardmarket')
        ),

    CONSTRAINT cards_source_card_id_check
        CHECK (
            source_card_id = btrim(source_card_id)
            AND source_card_id <> ''
        ),

    CONSTRAINT cards_collector_number_check
        CHECK (
            collector_number = btrim(collector_number)
            AND collector_number <> ''
        ),

    CONSTRAINT cards_name_check
        CHECK (btrim(name) <> ''),

    CONSTRAINT cards_rarity_check
        CHECK (
            rarity IS NULL
            OR btrim(rarity) <> ''
        ),

    CONSTRAINT cards_image_small_url_check
        CHECK (
            image_small_url IS NULL
            OR btrim(image_small_url) <> ''
        ),

    CONSTRAINT cards_image_large_url_check
        CHECK (
            image_large_url IS NULL
            OR btrim(image_large_url) <> ''
        ),

    CONSTRAINT cards_lifecycle_check
        CHECK (
            (is_active = true AND retired_at IS NULL)
            OR
            (is_active = false AND retired_at IS NOT NULL)
        )
);

CREATE TABLE public.card_editions (
    card_edition_id bigint GENERATED BY DEFAULT AS IDENTITY,
    card_id bigint NOT NULL,
    edition_key text NOT NULL,
    source_system text,
    source_edition_code text,
    display_name text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    retired_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT card_editions_pkey
        PRIMARY KEY (card_edition_id),

    CONSTRAINT card_editions_card_edition_key
        UNIQUE (card_id, edition_key),

    CONSTRAINT card_editions_hierarchy_key
        UNIQUE (card_edition_id, card_id),

    CONSTRAINT card_editions_card_fk
        FOREIGN KEY (card_id)
        REFERENCES public.cards (card_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_editions_edition_key_check
        CHECK (
            edition_key = btrim(edition_key)
            AND edition_key <> ''
        ),

    CONSTRAINT card_editions_display_name_check
        CHECK (btrim(display_name) <> ''),

    CONSTRAINT card_editions_source_pair_check
        CHECK (
            (
                source_system IS NULL
                AND source_edition_code IS NULL
            )
            OR
            (
                source_system = 'cardmarket'
                AND source_system = btrim(source_system)
                AND source_edition_code = btrim(source_edition_code)
                AND source_edition_code <> ''
            )
        ),

    CONSTRAINT card_editions_lifecycle_check
        CHECK (
            (is_active = true AND retired_at IS NULL)
            OR
            (is_active = false AND retired_at IS NOT NULL)
        )
);

CREATE UNIQUE INDEX card_editions_source_edition_key
    ON public.card_editions (
        card_id,
        source_system,
        source_edition_code
    )
    WHERE source_system IS NOT NULL
      AND source_edition_code IS NOT NULL;

CREATE TABLE public.card_variants (
    card_variant_id bigint GENERATED BY DEFAULT AS IDENTITY,
    card_edition_id bigint NOT NULL,
    language_code text NOT NULL,
    finish_code text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    retired_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT card_variants_pkey
        PRIMARY KEY (card_variant_id),

    CONSTRAINT card_variants_identity_key
        UNIQUE (
            card_edition_id,
            language_code,
            finish_code
        ),

    CONSTRAINT card_variants_hierarchy_key
        UNIQUE (
            card_variant_id,
            card_edition_id
        ),

    CONSTRAINT card_variants_edition_fk
        FOREIGN KEY (card_edition_id)
        REFERENCES public.card_editions (card_edition_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT card_variants_language_code_check
        CHECK (
            language_code = btrim(language_code)
            AND language_code IN ('en', 'de')
        ),

    CONSTRAINT card_variants_finish_code_check
        CHECK (
            finish_code = btrim(finish_code)
            AND finish_code IN (
                'normal',
                'reverse_holo',
                'holo'
            )
        ),

    CONSTRAINT card_variants_lifecycle_check
        CHECK (
            (is_active = true AND retired_at IS NULL)
            OR
            (is_active = false AND retired_at IS NOT NULL)
        )
);

CREATE INDEX expansion_source_identifiers_expansion_id_idx
    ON public.expansion_source_identifiers (expansion_id);

CREATE INDEX cards_expansion_id_idx
    ON public.cards (expansion_id);

CREATE INDEX card_editions_card_id_idx
    ON public.card_editions (card_id);

CREATE INDEX card_variants_card_edition_id_idx
    ON public.card_variants (card_edition_id);


-- migrate:down

DROP TABLE public.card_variants;
DROP TABLE public.card_editions;
DROP TABLE public.cards;
DROP TABLE public.expansion_source_identifiers;
DROP TABLE public.expansions;
