-- migrate:up

CREATE TABLE public.staging_market_prices (
    staging_market_price_id bigint GENERATED BY DEFAULT AS IDENTITY,
    import_run_id bigint NOT NULL,
    source_record_reference text NOT NULL,
    source_system text NOT NULL,
    source_product_id text,
    source_snapshot_at timestamp with time zone,
    currency_code text,
    avg30_raw text,
    avg30 numeric(12, 4),
    avg30_holo_raw text,
    avg30_holo numeric(12, 4),
    raw_payload jsonb NOT NULL,
    record_checksum text,
    normalization_status text NOT NULL DEFAULT 'pending',
    validation_status text NOT NULL DEFAULT 'pending',
    validation_completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT staging_market_prices_pkey
        PRIMARY KEY (staging_market_price_id),

    CONSTRAINT staging_market_prices_source_record_key
        UNIQUE (
            import_run_id,
            source_record_reference
        ),

    CONSTRAINT staging_market_prices_import_run_fk
        FOREIGN KEY (import_run_id)
        REFERENCES public.import_runs (import_run_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT staging_market_prices_source_record_reference_check
        CHECK (
            source_record_reference = btrim(source_record_reference)
            AND source_record_reference <> ''
        ),

    CONSTRAINT staging_market_prices_source_system_check
        CHECK (
            source_system = btrim(source_system)
            AND source_system = 'cardmarket'
        ),

    CONSTRAINT staging_market_prices_source_product_id_check
        CHECK (
            source_product_id IS NULL
            OR (
                source_product_id = btrim(source_product_id)
                AND source_product_id <> ''
            )
        ),

    CONSTRAINT staging_market_prices_currency_code_check
        CHECK (
            currency_code IS NULL
            OR (
                currency_code = btrim(currency_code)
                AND currency_code = 'EUR'
            )
        ),

    CONSTRAINT staging_market_prices_avg30_raw_check
        CHECK (
            avg30_raw IS NULL
            OR btrim(avg30_raw) <> ''
        ),

    CONSTRAINT staging_market_prices_avg30_holo_raw_check
        CHECK (
            avg30_holo_raw IS NULL
            OR btrim(avg30_holo_raw) <> ''
        ),

    CONSTRAINT staging_market_prices_record_checksum_check
        CHECK (
            record_checksum IS NULL
            OR (
                record_checksum = btrim(record_checksum)
                AND record_checksum <> ''
            )
        ),

    CONSTRAINT staging_market_prices_normalization_status_check
        CHECK (
            normalization_status IN (
                'pending',
                'normalized',
                'normalization_failed'
            )
        ),

    CONSTRAINT staging_market_prices_validation_status_check
        CHECK (
            validation_status IN (
                'pending',
                'valid',
                'rejected'
            )
        ),

    CONSTRAINT staging_market_prices_validation_state_check
        CHECK (
            validation_status <> 'valid'
            OR normalization_status = 'normalized'
        ),

    CONSTRAINT staging_market_prices_valid_record_check
        CHECK (
            validation_status <> 'valid'
            OR (
                source_product_id IS NOT NULL
                AND source_snapshot_at IS NOT NULL
                AND currency_code = 'EUR'
                AND (avg30 IS NULL OR avg30 >= 0)
                AND (avg30_holo IS NULL OR avg30_holo >= 0)
                AND (
                    avg30 IS NOT NULL
                    OR avg30_holo IS NOT NULL
                )
            )
        ),

    CONSTRAINT staging_market_prices_validation_timestamp_check
        CHECK (
            (
                validation_status = 'pending'
                AND validation_completed_at IS NULL
            )
            OR
            (
                validation_status IN ('valid', 'rejected')
                AND validation_completed_at IS NOT NULL
            )
        )
);

CREATE INDEX staging_market_prices_import_run_status_idx
    ON public.staging_market_prices (
        import_run_id,
        validation_status
    );

CREATE INDEX staging_market_prices_source_snapshot_idx
    ON public.staging_market_prices (
        import_run_id,
        source_system,
        source_product_id,
        source_snapshot_at
    )
    WHERE source_product_id IS NOT NULL;

CREATE INDEX staging_market_prices_currency_idx
    ON public.staging_market_prices (
        import_run_id,
        currency_code
    )
    WHERE currency_code IS NOT NULL;

CREATE INDEX staging_market_prices_pending_idx
    ON public.staging_market_prices (import_run_id)
    WHERE normalization_status = 'pending'
       OR validation_status = 'pending';


-- migrate:down

DROP TABLE public.staging_market_prices;
