-- migrate:up

CREATE TABLE public.rejected_source_records (
    rejected_source_record_id bigint GENERATED BY DEFAULT AS IDENTITY,
    import_run_id bigint NOT NULL,
    source_record_reference text NOT NULL,
    source_system text NOT NULL,
    source_entity_type text NOT NULL,
    source_entity_id text,
    rejection_stage text NOT NULL,
    rejection_status text NOT NULL DEFAULT 'open',
    raw_payload jsonb NOT NULL,
    normalized_payload jsonb,
    record_checksum text,
    first_rejected_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at timestamp with time zone,
    resolution_note text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT rejected_source_records_pkey
        PRIMARY KEY (rejected_source_record_id),

    CONSTRAINT rejected_source_records_run_reference_key
        UNIQUE (
            import_run_id,
            source_record_reference
        ),

    CONSTRAINT rejected_source_records_import_run_fk
        FOREIGN KEY (import_run_id)
        REFERENCES public.import_runs (import_run_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT rejected_source_records_source_record_reference_check
        CHECK (
            source_record_reference = btrim(source_record_reference)
            AND source_record_reference <> ''
        ),

    CONSTRAINT rejected_source_records_source_system_check
        CHECK (
            source_system = btrim(source_system)
            AND source_system IN (
                'pokemon_tcg_data',
                'cardmarket'
            )
        ),

    CONSTRAINT rejected_source_records_source_entity_type_check
        CHECK (
            source_entity_type = btrim(source_entity_type)
            AND source_entity_type IN (
                'card',
                'market_product',
                'market_price',
                'market_mapping'
            )
        ),

    CONSTRAINT rejected_source_records_source_entity_id_check
        CHECK (
            source_entity_id IS NULL
            OR (
                source_entity_id = btrim(source_entity_id)
                AND source_entity_id <> ''
            )
        ),

    CONSTRAINT rejected_source_records_rejection_stage_check
        CHECK (
            rejection_stage = btrim(rejection_stage)
            AND rejection_stage IN (
                'ingestion',
                'normalization',
                'validation',
                'merge'
            )
        ),

    CONSTRAINT rejected_source_records_rejection_status_check
        CHECK (
            rejection_status = btrim(rejection_status)
            AND rejection_status IN (
                'open',
                'resolved',
                'waived'
            )
        ),

    CONSTRAINT rejected_source_records_record_checksum_check
        CHECK (
            record_checksum IS NULL
            OR (
                record_checksum = btrim(record_checksum)
                AND record_checksum <> ''
            )
        ),

    CONSTRAINT rejected_source_records_resolution_note_check
        CHECK (
            resolution_note IS NULL
            OR btrim(resolution_note) <> ''
        ),

    CONSTRAINT rejected_source_records_resolution_state_check
        CHECK (
            (
                rejection_status = 'open'
                AND resolved_at IS NULL
                AND resolution_note IS NULL
            )
            OR
            (
                rejection_status IN ('resolved', 'waived')
                AND resolved_at IS NOT NULL
                AND resolution_note IS NOT NULL
            )
        )
);

CREATE INDEX rejected_source_records_run_status_idx
    ON public.rejected_source_records (
        import_run_id,
        rejection_status
    );

CREATE INDEX rejected_source_records_source_identity_idx
    ON public.rejected_source_records (
        source_system,
        source_entity_type,
        source_entity_id
    )
    WHERE source_entity_id IS NOT NULL;

CREATE INDEX rejected_source_records_open_idx
    ON public.rejected_source_records (
        first_rejected_at
    )
    WHERE rejection_status = 'open';


-- migrate:down

DROP TABLE public.rejected_source_records;
