-- migrate:up

CREATE TABLE public.staging_cards (
    staging_card_id bigint GENERATED BY DEFAULT AS IDENTITY,
    import_run_id bigint NOT NULL,
    source_record_reference text NOT NULL,
    source_system text NOT NULL,
    source_card_id text,
    source_expansion_id text,
    collector_number text,
    name text,
    rarity text,
    image_small_url text,
    image_large_url text,
    raw_payload jsonb NOT NULL,
    record_checksum text,
    normalization_status text NOT NULL DEFAULT 'pending',
    validation_status text NOT NULL DEFAULT 'pending',
    validation_completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT staging_cards_pkey
        PRIMARY KEY (staging_card_id),

    CONSTRAINT staging_cards_source_record_key
        UNIQUE (
            import_run_id,
            source_record_reference
        ),

    CONSTRAINT staging_cards_import_run_fk
        FOREIGN KEY (import_run_id)
        REFERENCES public.import_runs (import_run_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT staging_cards_source_record_reference_check
        CHECK (
            source_record_reference = btrim(source_record_reference)
            AND source_record_reference <> ''
        ),

    CONSTRAINT staging_cards_source_system_check
        CHECK (
            source_system = btrim(source_system)
            AND source_system = 'pokemon_tcg_data'
        ),

    CONSTRAINT staging_cards_source_card_id_check
        CHECK (
            source_card_id IS NULL
            OR (
                source_card_id = btrim(source_card_id)
                AND source_card_id <> ''
            )
        ),

    CONSTRAINT staging_cards_source_expansion_id_check
        CHECK (
            source_expansion_id IS NULL
            OR (
                source_expansion_id = btrim(source_expansion_id)
                AND source_expansion_id <> ''
            )
        ),

    CONSTRAINT staging_cards_collector_number_check
        CHECK (
            collector_number IS NULL
            OR (
                collector_number = btrim(collector_number)
                AND collector_number <> ''
            )
        ),

    CONSTRAINT staging_cards_name_check
        CHECK (
            name IS NULL
            OR btrim(name) <> ''
        ),

    CONSTRAINT staging_cards_rarity_check
        CHECK (
            rarity IS NULL
            OR btrim(rarity) <> ''
        ),

    CONSTRAINT staging_cards_image_small_url_check
        CHECK (
            image_small_url IS NULL
            OR btrim(image_small_url) <> ''
        ),

    CONSTRAINT staging_cards_image_large_url_check
        CHECK (
            image_large_url IS NULL
            OR btrim(image_large_url) <> ''
        ),

    CONSTRAINT staging_cards_record_checksum_check
        CHECK (
            record_checksum IS NULL
            OR (
                record_checksum = btrim(record_checksum)
                AND record_checksum <> ''
            )
        ),

    CONSTRAINT staging_cards_normalization_status_check
        CHECK (
            normalization_status IN (
                'pending',
                'normalized',
                'normalization_failed'
            )
        ),

    CONSTRAINT staging_cards_validation_status_check
        CHECK (
            validation_status IN (
                'pending',
                'valid',
                'rejected'
            )
        ),

    CONSTRAINT staging_cards_validation_state_check
        CHECK (
            validation_status <> 'valid'
            OR normalization_status = 'normalized'
        ),

    CONSTRAINT staging_cards_validation_timestamp_check
        CHECK (
            (
                validation_status = 'pending'
                AND validation_completed_at IS NULL
            )
            OR
            (
                validation_status IN ('valid', 'rejected')
                AND validation_completed_at IS NOT NULL
            )
        )
);

CREATE INDEX staging_cards_import_run_status_idx
    ON public.staging_cards (
        import_run_id,
        validation_status
    );

CREATE INDEX staging_cards_source_identity_idx
    ON public.staging_cards (
        import_run_id,
        source_system,
        source_card_id
    )
    WHERE source_card_id IS NOT NULL;

CREATE INDEX staging_cards_pending_idx
    ON public.staging_cards (import_run_id)
    WHERE normalization_status = 'pending'
       OR validation_status = 'pending';


-- migrate:down

DROP TABLE public.staging_cards;
