-- migrate:up

CREATE TABLE public.staging_market_products (
    staging_market_product_id bigint GENERATED BY DEFAULT AS IDENTITY,
    import_run_id bigint NOT NULL,
    source_record_reference text NOT NULL,
    source_system text NOT NULL,
    source_product_id text,
    source_expansion_id text,
    source_metaproduct_id text,
    raw_name text,
    source_category_id text,
    source_category_name text,
    source_created_at timestamp with time zone,
    raw_payload jsonb NOT NULL,
    record_checksum text,
    normalization_status text NOT NULL DEFAULT 'pending',
    validation_status text NOT NULL DEFAULT 'pending',
    validation_completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT staging_market_products_pkey
        PRIMARY KEY (staging_market_product_id),

    CONSTRAINT staging_market_products_source_record_key
        UNIQUE (
            import_run_id,
            source_record_reference
        ),

    CONSTRAINT staging_market_products_import_run_fk
        FOREIGN KEY (import_run_id)
        REFERENCES public.import_runs (import_run_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT staging_market_products_source_record_reference_check
        CHECK (
            source_record_reference = btrim(source_record_reference)
            AND source_record_reference <> ''
        ),

    CONSTRAINT staging_market_products_source_system_check
        CHECK (
            source_system = btrim(source_system)
            AND source_system = 'cardmarket'
        ),

    CONSTRAINT staging_market_products_source_product_id_check
        CHECK (
            source_product_id IS NULL
            OR (
                source_product_id = btrim(source_product_id)
                AND source_product_id <> ''
            )
        ),

    CONSTRAINT staging_market_products_source_expansion_id_check
        CHECK (
            source_expansion_id IS NULL
            OR (
                source_expansion_id = btrim(source_expansion_id)
                AND source_expansion_id <> ''
            )
        ),

    CONSTRAINT staging_market_products_source_metaproduct_id_check
        CHECK (
            source_metaproduct_id IS NULL
            OR (
                source_metaproduct_id = btrim(source_metaproduct_id)
                AND source_metaproduct_id <> ''
            )
        ),

    CONSTRAINT staging_market_products_raw_name_check
        CHECK (
            raw_name IS NULL
            OR btrim(raw_name) <> ''
        ),

    CONSTRAINT staging_market_products_source_category_id_check
        CHECK (
            source_category_id IS NULL
            OR (
                source_category_id = btrim(source_category_id)
                AND source_category_id <> ''
            )
        ),

    CONSTRAINT staging_market_products_source_category_name_check
        CHECK (
            source_category_name IS NULL
            OR btrim(source_category_name) <> ''
        ),

    CONSTRAINT staging_market_products_record_checksum_check
        CHECK (
            record_checksum IS NULL
            OR (
                record_checksum = btrim(record_checksum)
                AND record_checksum <> ''
            )
        ),

    CONSTRAINT staging_market_products_normalization_status_check
        CHECK (
            normalization_status IN (
                'pending',
                'normalized',
                'normalization_failed'
            )
        ),

    CONSTRAINT staging_market_products_validation_status_check
        CHECK (
            validation_status IN (
                'pending',
                'valid',
                'rejected'
            )
        ),

    CONSTRAINT staging_market_products_validation_state_check
        CHECK (
            validation_status <> 'valid'
            OR normalization_status = 'normalized'
        ),

    CONSTRAINT staging_market_products_valid_record_check
        CHECK (
            validation_status <> 'valid'
            OR (
                source_product_id IS NOT NULL
                AND raw_name IS NOT NULL
            )
        ),

    CONSTRAINT staging_market_products_validation_timestamp_check
        CHECK (
            (
                validation_status = 'pending'
                AND validation_completed_at IS NULL
            )
            OR
            (
                validation_status IN ('valid', 'rejected')
                AND validation_completed_at IS NOT NULL
            )
        )
);

CREATE INDEX staging_market_products_import_run_status_idx
    ON public.staging_market_products (
        import_run_id,
        validation_status
    );

CREATE INDEX staging_market_products_source_identity_idx
    ON public.staging_market_products (
        import_run_id,
        source_system,
        source_product_id
    )
    WHERE source_product_id IS NOT NULL;

CREATE INDEX staging_market_products_source_expansion_idx
    ON public.staging_market_products (
        import_run_id,
        source_expansion_id
    )
    WHERE source_expansion_id IS NOT NULL;

CREATE INDEX staging_market_products_pending_idx
    ON public.staging_market_products (import_run_id)
    WHERE normalization_status = 'pending'
       OR validation_status = 'pending';


-- migrate:down

DROP TABLE public.staging_market_products;
