-- migrate:up

CREATE TABLE public.import_runs (
    import_run_id bigint GENERATED BY DEFAULT AS IDENTITY,
    run_reference text NOT NULL,
    run_kind text NOT NULL,
    source_system text NOT NULL,
    source_entity_type text NOT NULL,
    source_artifact_reference text NOT NULL,
    source_artifact_checksum text,
    scope_type text NOT NULL,
    scope_reference text NOT NULL,
    is_authoritative boolean NOT NULL DEFAULT false,
    status text NOT NULL DEFAULT 'created',
    started_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    staging_loaded_at timestamp with time zone,
    validated_at timestamp with time zone,
    merge_started_at timestamp with time zone,
    completed_at timestamp with time zone,
    failure_code text,
    failure_detail text,
    importer_version text NOT NULL,
    total_source_records integer,
    valid_source_records integer,
    rejected_records integer,
    inserted_records integer,
    updated_records integer,
    unchanged_records integer,
    missing_records integer,
    retired_records integer,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT import_runs_pkey
        PRIMARY KEY (import_run_id),

    CONSTRAINT import_runs_run_reference_key
        UNIQUE (run_reference),

    CONSTRAINT import_runs_run_reference_check
        CHECK (
            run_reference = btrim(run_reference)
            AND run_reference <> ''
        ),

    CONSTRAINT import_runs_run_kind_check
        CHECK (
            run_kind = btrim(run_kind)
            AND run_kind IN (
                'catalogue',
                'market_products',
                'market_prices',
                'market_mappings'
            )
        ),

    CONSTRAINT import_runs_source_system_check
        CHECK (
            source_system = btrim(source_system)
            AND source_system IN (
                'pokemon_tcg_data',
                'cardmarket'
            )
        ),

    CONSTRAINT import_runs_source_entity_type_check
        CHECK (
            source_entity_type = btrim(source_entity_type)
            AND source_entity_type IN (
                'card',
                'market_product',
                'market_price',
                'market_mapping'
            )
        ),

    CONSTRAINT import_runs_source_artifact_reference_check
        CHECK (
            source_artifact_reference = btrim(source_artifact_reference)
            AND source_artifact_reference <> ''
        ),

    CONSTRAINT import_runs_source_artifact_checksum_check
        CHECK (
            source_artifact_checksum IS NULL
            OR (
                source_artifact_checksum = btrim(source_artifact_checksum)
                AND source_artifact_checksum <> ''
            )
        ),

    CONSTRAINT import_runs_scope_type_check
        CHECK (
            scope_type = btrim(scope_type)
            AND scope_type IN (
                'expansion',
                'source_file',
                'selected_records',
                'complete_source_snapshot'
            )
        ),

    CONSTRAINT import_runs_scope_reference_check
        CHECK (
            scope_reference = btrim(scope_reference)
            AND scope_reference <> ''
        ),

    CONSTRAINT import_runs_status_check
        CHECK (
            status = btrim(status)
            AND status IN (
                'created',
                'staging_loaded',
                'validation_failed',
                'validated',
                'merge_started',
                'merge_failed',
                'succeeded',
                'cancelled'
            )
        ),

    CONSTRAINT import_runs_importer_version_check
        CHECK (
            importer_version = btrim(importer_version)
            AND importer_version <> ''
        ),

    CONSTRAINT import_runs_failure_code_check
        CHECK (
            failure_code IS NULL
            OR (
                failure_code = btrim(failure_code)
                AND failure_code <> ''
            )
        ),

    CONSTRAINT import_runs_failure_detail_check
        CHECK (
            failure_detail IS NULL
            OR btrim(failure_detail) <> ''
        ),

    CONSTRAINT import_runs_terminal_completion_check
        CHECK (
            (
                status IN (
                    'validation_failed',
                    'merge_failed',
                    'succeeded',
                    'cancelled'
                )
                AND completed_at IS NOT NULL
            )
            OR
            (
                status IN (
                    'created',
                    'staging_loaded',
                    'validated',
                    'merge_started'
                )
                AND completed_at IS NULL
            )
        ),

    CONSTRAINT import_runs_failure_fields_check
        CHECK (
            (
                status IN ('validation_failed', 'merge_failed')
                AND failure_code IS NOT NULL
            )
            OR
            (
                status = 'succeeded'
                AND failure_code IS NULL
                AND failure_detail IS NULL
            )
            OR
            status IN (
                'created',
                'staging_loaded',
                'validated',
                'merge_started',
                'cancelled'
            )
        ),

    CONSTRAINT import_runs_timestamp_order_check
        CHECK (
            (staging_loaded_at IS NULL OR started_at <= staging_loaded_at)
            AND
            (
                validated_at IS NULL
                OR (
                    staging_loaded_at IS NOT NULL
                    AND staging_loaded_at <= validated_at
                )
            )
            AND
            (
                merge_started_at IS NULL
                OR (
                    validated_at IS NOT NULL
                    AND validated_at <= merge_started_at
                )
            )
            AND
            (
                completed_at IS NULL
                OR started_at <= completed_at
            )
            AND
            (
                completed_at IS NULL
                OR staging_loaded_at IS NULL
                OR staging_loaded_at <= completed_at
            )
            AND
            (
                completed_at IS NULL
                OR validated_at IS NULL
                OR validated_at <= completed_at
            )
            AND
            (
                completed_at IS NULL
                OR merge_started_at IS NULL
                OR merge_started_at <= completed_at
            )
        ),

    CONSTRAINT import_runs_summary_counts_check
        CHECK (
            (total_source_records IS NULL OR total_source_records >= 0)
            AND (valid_source_records IS NULL OR valid_source_records >= 0)
            AND (rejected_records IS NULL OR rejected_records >= 0)
            AND (inserted_records IS NULL OR inserted_records >= 0)
            AND (updated_records IS NULL OR updated_records >= 0)
            AND (unchanged_records IS NULL OR unchanged_records >= 0)
            AND (missing_records IS NULL OR missing_records >= 0)
            AND (retired_records IS NULL OR retired_records >= 0)
        ),

    CONSTRAINT import_runs_success_summary_check
        CHECK (
            status <> 'succeeded'
            OR (
                total_source_records IS NOT NULL
                AND valid_source_records IS NOT NULL
                AND rejected_records IS NOT NULL
                AND inserted_records IS NOT NULL
                AND updated_records IS NOT NULL
                AND unchanged_records IS NOT NULL
                AND missing_records IS NOT NULL
                AND retired_records IS NOT NULL
                AND total_source_records
                    = valid_source_records + rejected_records
            )
        ),

    CONSTRAINT import_runs_authoritative_missing_check
        CHECK (
            missing_records IS NULL
            OR missing_records = 0
            OR is_authoritative = true
        )
);

CREATE INDEX import_runs_status_idx
    ON public.import_runs (status);

CREATE INDEX import_runs_run_kind_idx
    ON public.import_runs (run_kind);

CREATE INDEX import_runs_started_at_idx
    ON public.import_runs (started_at DESC);

CREATE INDEX import_runs_scope_status_idx
    ON public.import_runs (
        source_system,
        scope_type,
        scope_reference,
        status,
        completed_at DESC
    );

CREATE INDEX import_runs_active_idx
    ON public.import_runs (started_at DESC)
    WHERE status IN (
        'created',
        'staging_loaded',
        'validated',
        'merge_started'
    );


-- migrate:down

DROP TABLE public.import_runs;
