-- migrate:up

CREATE TABLE public.mapping_status_history (
    mapping_status_history_id bigint GENERATED BY DEFAULT AS IDENTITY,
    mapping_case_id bigint NOT NULL,
    mapping_case_observation_id bigint,
    previous_status text,
    new_status text NOT NULL,
    previous_confirmation_scope text,
    new_confirmation_scope text,
    previous_card_id bigint,
    new_card_id bigint,
    previous_card_edition_id bigint,
    new_card_edition_id bigint,
    previous_card_variant_id bigint,
    new_card_variant_id bigint,
    transition_reason_code text NOT NULL,
    transition_reason_detail text,
    changed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT mapping_status_history_pkey
        PRIMARY KEY (mapping_status_history_id),

    CONSTRAINT mapping_status_history_case_fk
        FOREIGN KEY (mapping_case_id)
        REFERENCES public.card_market_mapping_cases (mapping_case_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_status_history_observation_case_fk
        FOREIGN KEY (
            mapping_case_observation_id,
            mapping_case_id
        )
        REFERENCES public.mapping_case_observations (
            mapping_case_observation_id,
            mapping_case_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_status_history_previous_card_fk
        FOREIGN KEY (previous_card_id)
        REFERENCES public.cards (card_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_status_history_new_card_fk
        FOREIGN KEY (new_card_id)
        REFERENCES public.cards (card_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_status_history_previous_edition_fk
        FOREIGN KEY (
            previous_card_edition_id,
            previous_card_id
        )
        REFERENCES public.card_editions (
            card_edition_id,
            card_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_status_history_new_edition_fk
        FOREIGN KEY (
            new_card_edition_id,
            new_card_id
        )
        REFERENCES public.card_editions (
            card_edition_id,
            card_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_status_history_previous_variant_fk
        FOREIGN KEY (
            previous_card_variant_id,
            previous_card_edition_id
        )
        REFERENCES public.card_variants (
            card_variant_id,
            card_edition_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_status_history_new_variant_fk
        FOREIGN KEY (
            new_card_variant_id,
            new_card_edition_id
        )
        REFERENCES public.card_variants (
            card_variant_id,
            card_edition_id
        )
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT mapping_status_history_previous_status_check
        CHECK (
            previous_status IS NULL
            OR previous_status IN (
                'confirmed',
                'candidate',
                'unmatched',
                'ambiguous',
                'excluded',
                'unmatched_duplicate_candidate'
            )
        ),

    CONSTRAINT mapping_status_history_new_status_check
        CHECK (
            new_status IN (
                'confirmed',
                'candidate',
                'unmatched',
                'ambiguous',
                'excluded',
                'unmatched_duplicate_candidate'
            )
        ),

    CONSTRAINT mapping_status_history_previous_scope_check
        CHECK (
            previous_confirmation_scope IS NULL
            OR previous_confirmation_scope IN (
                'card',
                'edition',
                'variant'
            )
        ),

    CONSTRAINT mapping_status_history_new_scope_check
        CHECK (
            new_confirmation_scope IS NULL
            OR new_confirmation_scope IN (
                'card',
                'edition',
                'variant'
            )
        ),

    CONSTRAINT mapping_status_history_reason_code_check
        CHECK (
            transition_reason_code = btrim(transition_reason_code)
            AND transition_reason_code <> ''
        ),

    CONSTRAINT mapping_status_history_reason_detail_check
        CHECK (
            transition_reason_detail IS NULL
            OR btrim(transition_reason_detail) <> ''
        ),

    CONSTRAINT mapping_status_history_previous_state_check
        CHECK (
            (
                previous_status = 'confirmed'
                AND previous_confirmation_scope IS NOT NULL
                AND previous_card_id IS NOT NULL
            )
            OR
            (
                previous_status IS DISTINCT FROM 'confirmed'
                AND previous_confirmation_scope IS NULL
                AND previous_card_id IS NULL
                AND previous_card_edition_id IS NULL
                AND previous_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_status_history_new_state_check
        CHECK (
            (
                new_status = 'confirmed'
                AND new_confirmation_scope IS NOT NULL
                AND new_card_id IS NOT NULL
            )
            OR
            (
                new_status <> 'confirmed'
                AND new_confirmation_scope IS NULL
                AND new_card_id IS NULL
                AND new_card_edition_id IS NULL
                AND new_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_status_history_previous_card_scope_check
        CHECK (
            previous_confirmation_scope <> 'card'
            OR (
                previous_card_id IS NOT NULL
                AND previous_card_edition_id IS NULL
                AND previous_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_status_history_previous_edition_scope_check
        CHECK (
            previous_confirmation_scope <> 'edition'
            OR (
                previous_card_id IS NOT NULL
                AND previous_card_edition_id IS NOT NULL
                AND previous_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_status_history_previous_variant_scope_check
        CHECK (
            previous_confirmation_scope <> 'variant'
            OR (
                previous_card_id IS NOT NULL
                AND previous_card_edition_id IS NOT NULL
                AND previous_card_variant_id IS NOT NULL
            )
        ),

    CONSTRAINT mapping_status_history_new_card_scope_check
        CHECK (
            new_confirmation_scope <> 'card'
            OR (
                new_card_id IS NOT NULL
                AND new_card_edition_id IS NULL
                AND new_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_status_history_new_edition_scope_check
        CHECK (
            new_confirmation_scope <> 'edition'
            OR (
                new_card_id IS NOT NULL
                AND new_card_edition_id IS NOT NULL
                AND new_card_variant_id IS NULL
            )
        ),

    CONSTRAINT mapping_status_history_new_variant_scope_check
        CHECK (
            new_confirmation_scope <> 'variant'
            OR (
                new_card_id IS NOT NULL
                AND new_card_edition_id IS NOT NULL
                AND new_card_variant_id IS NOT NULL
            )
        )
);

CREATE INDEX mapping_status_history_case_changed_idx
    ON public.mapping_status_history (
        mapping_case_id,
        changed_at DESC
    );

CREATE INDEX mapping_status_history_observation_idx
    ON public.mapping_status_history (
        mapping_case_observation_id
    )
    WHERE mapping_case_observation_id IS NOT NULL;

CREATE INDEX mapping_status_history_new_status_idx
    ON public.mapping_status_history (
        new_status,
        changed_at DESC
    );


-- migrate:down

DROP TABLE public.mapping_status_history;
