-- migrate:up

CREATE TABLE public.market_price_snapshots (
    market_price_snapshot_id bigint GENERATED BY DEFAULT AS IDENTITY,
    market_product_id bigint NOT NULL,
    import_run_id bigint NOT NULL,
    source_snapshot_at timestamp with time zone NOT NULL,
    currency_code text NOT NULL,
    avg30 numeric(12, 4),
    avg30_holo numeric(12, 4),
    source_record_reference text NOT NULL,
    record_checksum text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT market_price_snapshots_pkey
        PRIMARY KEY (market_price_snapshot_id),

    CONSTRAINT market_price_snapshots_product_timestamp_key
        UNIQUE (
            market_product_id,
            source_snapshot_at
        ),

    CONSTRAINT market_price_snapshots_market_product_fk
        FOREIGN KEY (market_product_id)
        REFERENCES public.market_products (market_product_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT market_price_snapshots_import_run_fk
        FOREIGN KEY (import_run_id)
        REFERENCES public.import_runs (import_run_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT market_price_snapshots_currency_check
        CHECK (
            currency_code = btrim(currency_code)
            AND currency_code = 'EUR'
        ),

    CONSTRAINT market_price_snapshots_avg30_check
        CHECK (
            avg30 IS NULL
            OR avg30 >= 0
        ),

    CONSTRAINT market_price_snapshots_avg30_holo_check
        CHECK (
            avg30_holo IS NULL
            OR avg30_holo >= 0
        ),

    CONSTRAINT market_price_snapshots_price_presence_check
        CHECK (
            avg30 IS NOT NULL
            OR avg30_holo IS NOT NULL
        ),

    CONSTRAINT market_price_snapshots_source_reference_check
        CHECK (
            source_record_reference = btrim(source_record_reference)
            AND source_record_reference <> ''
        ),

    CONSTRAINT market_price_snapshots_record_checksum_check
        CHECK (
            record_checksum IS NULL
            OR (
                record_checksum = btrim(record_checksum)
                AND record_checksum <> ''
            )
        )
);

CREATE INDEX market_price_snapshots_product_latest_idx
    ON public.market_price_snapshots (
        market_product_id,
        source_snapshot_at DESC
    );

CREATE INDEX market_price_snapshots_import_run_idx
    ON public.market_price_snapshots (import_run_id);

CREATE INDEX market_price_snapshots_snapshot_at_idx
    ON public.market_price_snapshots (source_snapshot_at DESC);

CREATE INDEX market_price_snapshots_currency_snapshot_idx
    ON public.market_price_snapshots (
        currency_code,
        source_snapshot_at DESC
    );


-- migrate:down

DROP TABLE public.market_price_snapshots;
