"""
Script: analyze_primal_clash_mapping_review.py

Purpose:
    Analyse the generated Primal Clash mapping-review.csv file.

    The script reports mapping-status counts, canonical cards with multiple
    candidate rows, Cardmarket products referenced by multiple canonical cards,
    unmatched duplicate candidates, unmatched products, and excluded records.

Lifecycle:
    Permanent project utility.

Removal:
    Keep this script while Primal Clash remains the reference vertical slice.
    It may be replaced only by a generalized mapping-validation report that
    provides equivalent ambiguity and coverage diagnostics.
"""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_DIR = REPO_ROOT / "data" / "fixtures" / "primal-clash"

MAPPING_REVIEW_FILE = FIXTURE_DIR / "mapping-review.csv"


def require_file(path: Path) -> None:
    """Stop execution when the mapping review file does not exist."""
    if not path.is_file():
        raise FileNotFoundError(f"Required file not found: {path}")


def load_rows(path: Path) -> list[dict[str, str]]:
    """Load the UTF-8 CSV generated by the mapping-review builder."""
    with path.open("r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)

        required_columns = {
            "canonical_card_id",
            "collector_number",
            "canonical_name",
            "cardmarket_product_id",
            "cardmarket_product_name",
            "mapping_status",
            "evidence",
        }

        actual_columns = set(reader.fieldnames or [])
        missing_columns = required_columns - actual_columns

        if missing_columns:
            missing = ", ".join(sorted(missing_columns))
            raise ValueError(
                f"Missing columns in {path.name}: {missing}"
            )

        return [
            {
                key: (value or "").strip()
                for key, value in row.items()
            }
            for row in reader
        ]


def print_status_counts(rows: list[dict[str, str]]) -> None:
    """Print the number of rows in every mapping status."""
    counts: dict[str, int] = defaultdict(int)

    for row in rows:
        counts[row["mapping_status"]] += 1

    print("Mapping row status counts:")

    for status in sorted(counts):
        print(f"- {status}: {counts[status]:,}")


def print_ambiguous_cards(rows: list[dict[str, str]]) -> None:
    """Print canonical cards that have multiple ambiguous candidate rows."""
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)

    for row in rows:
        if row["mapping_status"] != "ambiguous":
            continue

        card_id = row["canonical_card_id"]

        if card_id:
            grouped[card_id].append(row)

    print()
    print(
        "Canonical cards with ambiguous mapping rows: "
        f"{len(grouped):,}"
    )

    for card_id in sorted(grouped):
        card_rows = grouped[card_id]
        first = card_rows[0]

        product_ids = sorted(
            {
                row["cardmarket_product_id"]
                for row in card_rows
                if row["cardmarket_product_id"]
            }
        )

        listing_urls = {
            row.get("listing_url", "")
            for row in card_rows
            if row.get("listing_url", "")
        }

        print(
            f"- {card_id} | #{first['collector_number']} | "
            f"{first['canonical_name']} | "
            f"{len(product_ids)} product(s) | "
            f"{len(listing_urls)} listing row(s) | "
            f"{len(card_rows)} review row(s)"
        )


def print_shared_products(rows: list[dict[str, str]]) -> None:
    """
    Print Cardmarket products linked as candidates to multiple canonical cards.

    These products cannot be confirmed until richer matching evidence is used.
    """
    product_to_cards: dict[str, set[str]] = defaultdict(set)
    product_names: dict[str, str] = {}

    for row in rows:
        if row["mapping_status"] not in {"candidate", "ambiguous"}:
            continue

        product_id = row["cardmarket_product_id"]
        card_id = row["canonical_card_id"]

        if not product_id or not card_id:
            continue

        product_to_cards[product_id].add(card_id)
        product_names[product_id] = row["cardmarket_product_name"]

    shared_products = {
        product_id: card_ids
        for product_id, card_ids in product_to_cards.items()
        if len(card_ids) > 1
    }

    print()
    print(
        "Cardmarket products referenced by multiple canonical cards: "
        f"{len(shared_products):,}"
    )

    for product_id in sorted(shared_products, key=int):
        card_ids = sorted(shared_products[product_id])

        print(
            f"- {product_id} | {product_names[product_id]} | "
            f"{len(card_ids)} canonical cards: "
            f"{', '.join(card_ids)}"
        )

def print_unmatched_duplicate_candidates(
    rows: list[dict[str, str]],
) -> None:
    """
    Print unlisted duplicate-like Cardmarket product records.

    These records remain preserved but are not mapped to canonical cards and
    do not participate in canonical price calculation.
    """
    candidates = [
        row
        for row in rows
        if (
            row["mapping_status"]
            == "unmatched_duplicate_candidate"
            and row["cardmarket_product_id"]
        )
    ]

    print()
    print(
        "Unmatched duplicate candidates: "
        f"{len(candidates):,}"
    )

    for row in sorted(
        candidates,
        key=lambda item: int(item["cardmarket_product_id"]),
    ):
        print(
            f"- {row['cardmarket_product_id']} | "
            f"idMetacard={row.get('cardmarket_metacard_id', '')} | "
            f"{row['cardmarket_product_name']} | "
            f"{row['evidence']}"
        )

def print_unmatched_products(rows: list[dict[str, str]]) -> None:
    """Print unmatched Cardmarket products."""
    unmatched = [
        row
        for row in rows
        if (
            row["mapping_status"] == "unmatched"
            and row["cardmarket_product_id"]
        )
    ]

    print()
    print(f"Unmatched Cardmarket products: {len(unmatched):,}")

    for row in sorted(
        unmatched,
        key=lambda item: int(item["cardmarket_product_id"]),
    ):
        print(
            f"- {row['cardmarket_product_id']} | "
            f"{row['cardmarket_product_name']} | "
            f"{row['evidence']}"
        )


def print_excluded_rows(rows: list[dict[str, str]]) -> None:
    """Print records explicitly excluded from the MVP card scope."""
    excluded = [
        row
        for row in rows
        if row["mapping_status"] == "excluded"
    ]

    print()
    print(f"Excluded review rows: {len(excluded):,}")

    for row in excluded:
        identity = (
            row["cardmarket_product_id"]
            or row.get("listing_url", "")
            or "no source identifier"
        )

        name = (
            row["cardmarket_product_name"]
            or row.get("listing_name", "")
            or "unnamed"
        )

        print(f"- {identity} | {name} | {row['evidence']}")


def main() -> None:
    require_file(MAPPING_REVIEW_FILE)

    rows = load_rows(MAPPING_REVIEW_FILE)

    print(f"Input file: {MAPPING_REVIEW_FILE}")
    print(f"Review rows: {len(rows):,}")
    print()

    print_status_counts(rows)
    print_ambiguous_cards(rows)
    print_shared_products(rows)
    print_unmatched_duplicate_candidates(rows)
    print_unmatched_products(rows)
    print_excluded_rows(rows)

    print()
    print("Mapping review analysis completed.")


if __name__ == "__main__":
    main()